### ISSUE TITLE
Serious var name parsing error

### ISSUE THREAD

**Issue by nixxon** [amasad/pg-basic#10]
If you try to run this short program
```
10 LET orgy = 42
20 PRINT orgy
```
you'll get the error: "**_ParseError: Parse error on line 10: Expected a variable after LET but got a logic instead_**".

It seems like pg-basic wrongly assume that variable orgy is beginning of logic operator OR.

**Comment by amasad** [comment]
I found out about this yesterday. I'll get a fix out asap

**Comment by amasad** [comment]
fixed in https://github.com/amasad/pg-basic/commit/b41f3b18f1a6dfd1dcde94382af64f0e814f277c

Well deploy soon.
